#!bin/env bash
export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"

# bruh
bindkey -e
# i hate my life
bindkey "^[[1;5C" forward-word # ctrl+right arrow
bindkey "^[[1;5D" backward-word # ctrl+left arrow
bindkey "^[[3;5~" kill-word # ctrl+delete
bindkey '^H' backward-kill-word # ctrl+backspace
bindkey '^[[H' beginning-of-line # home key
bindkey '^[[F' end-of-line # end key
bindkey  "^[[3~"  delete-char # too lazy to explain


# Where should I put you?
bindkey -s ^f "tmux-sessionizer\n"

f() {
    # Define the directory to search in
    local search_dir=${1:-$HOME}

    # Use find and fzf to select a directory
    local selected_dir=$(find "$search_dir" -type d 2>/dev/null | fzf)

    # Change directory if a selection was made
    if [ -n "$selected_dir" ]; then
        cd "$selected_dir"
    fi
}



