name: jellyfin-nvidia
services:
  jellyfin:
    cpu_shares: 90
    command: []
    container_name: jellyfin
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: "268435456"
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    devices:
      - /dev/dri:/dev/dri
      - /dev/vcsm:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    environment:
      - CPU_FALLBACK=true
      - NVIDIA_VISIBLE_DEVICES=all
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
    hostname: jellyfin
    image: linuxserver/jellyfin:10.10.6
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/icon.png
    ports:
      - target: 8096
        published: "8096"
        protocol: tcp
      - target: 8920
        published: "8921"
        protocol: tcp
      - target: 7359
        published: "7359"
        protocol: tcp
      - target: 1900
        published: "1901"
        protocol: tcp
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin-nvidia/config
        target: /config
      - type: bind
        source: /srv/jellyfin
        target: /Media
      - type: bind
        source: /opt/vc/lib
        target: /opt/vc/lib
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
        - container: PUID
          description:
            en_us: Run Jellyfin as specified uid.
            zh_cn: Jellyfin运行的用户ID
        - container: PGID
          description:
            en_us: Run Jellyfin as specified gid.
            zh_cn: Jellyfin运行的用户组ID
        - container: JELLYFIN_PublishedServerUrl
          description:
            en_us: The autodiscovery response domain or IP address.
            zh_cn: 自动发现响应域名或IP地址
      ports:
        - container: "8096"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口
        - container: "8920"
          description:
            en_us: WebUI HTTPS Port
            zh_cn: WebUI HTTPS端口
        - container: "7359"
          description:
            en_us: Jellyfin auto-discovery Port
            zh_cn: Jellyfin自动发现端口
        - container: "1900"
          description:
            en_us: Jellyfin DLNA Port
            zh_cn: Jellyfin DLNA端口
      volumes:
        - container: /config
          description:
            en_us: Jellyfin config directory.
            zh_cn: Jellyfin配置目录
        - container: /Media
          description:
            en_us: Jellyfin Media directory.
            zh_cn: Jellyfin媒体目录
        - container: /opt/vc/lib
          description:
            en_us: OpenMax libs
            zh_cn: OpenMax库
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: CasaOS Team
  category: Media
  description:
    ar_sa: يتيح لك Jellyfin جمع وإدارة وتدفق وسائطك. قم بتشغيل خادم Jellyfin على
      نظامك واحصل على النظام الرائد للترفيه المجاني ، مع الأجهزة الصوتية
      والمزايا المتضمنة.
    de_de: Jellyfin ermöglicht es Ihnen, Ihre Medien zu sammeln, zu verwalten und zu
      streamen. Führen Sie den Jellyfin-Server auf Ihrem System aus und erhalten
      Sie Zugriff auf das führende kostenlose Softwareunterhaltungssystem,
      inklusive Klingelton und Dekoration.
    en_us: >
      Imagine having all your movies, TV shows, and music at your fingertips,
      ready on any device. Jellyfin transforms your media collection into a
      personalized entertainment hub, surpassing traditional photo albums. Your
      media is accessible anywhere and beautifully organized.


      Jellyfin is free and open-source, offering high-quality streaming, detailed metadata, and personalized recommendations. Multiple users can have their own media libraries.


      Deploying Jellyfin on private cloud devices like Zima provides virtually unlimited storage, seamless streaming, and secure, multi-device access. It's perfect for NAS enthusiasts looking to enhance their home media setup.
    es_es: Jellyfin le permite recopilar, administrar y transmitir sus medios.
      Ejecute el servidor Jellyfin en su sistema y obtenga acceso al sistema de
      entretenimiento de software libre líder, con timbres y adornos incluidos.
    fr_fr: Jellyfin vous permet de collecter, de gérer et de diffuser vos médias.
      Exécutez le serveur Jellyfin sur votre système et accédez au système de
      divertissement logiciel libre de pointe, avec des sonneries et des
      décorations incluses.
    hu_hu: A Jellyfin lehetővé teszi, hogy gyűjtsön, kezeljen és adja tovább a
      médiaanyagait. Futtassa a Jellyfin szerverét a rendszerén, és hozzáférhet
      a vezető ingyenes szoftveres szórakoztató rendszerhez, csengőhangokkal és
      díszítésekkel.
    it_it: Jellyfin consente di raccogliere, gestire e trasmettere i tuoi media.
      Esegui il server Jellyfin sul tuo sistema e accedi al sistema di
      intrattenimento software libero leader, con suoni e decorazioni incluse.
    pl_pl: Jellyfin pozwala zbierać, zarządzać i przesyłać swoją multimedialną
      zawartość. Uruchom serwer Jellyfin na swoim systemie i uzyskaj dostęp do
      liderującego systemu rozrywki z otwartym oprogramowaniem, w tym dzwonków i
      ozdób.
    pt_br: O Jellyfin permite que você colete, gerencie e transmita seus meios de
      comunicação. Execute o servidor Jellyfin em seu sistema e obtenha acesso
      ao sistema de entretenimento de software livre líder, com toques e
      decorações incluídos.
    ru_ru: Jellyfin позволяет собирать, управлять и транслировать свою
      медиаинформацию. Запустите сервер Jellyfin на своей системе и получите
      доступ к лидирующей системе развлечений с открытым исходным кодом, включая
      звонки и украшения.
    sv_se: Jellyfin gör det möjligt att samla in, hantera och strömma dina medier.
      Kör Jellyfin-servern på ditt system och få tillgång till ledande
      underhållningssystem med fri mjukvara, med klockor och dekorationer
      inkluderade.
    uk_ua: Jellyfin дозволяє збирати, керувати та транслювати вашу медіаінформацію.
      Запустіть сервер Jellyfin на своєму системі та отримайте доступ до
      лідерської системи розваг з відкритим програмним забезпеченням, включаючи
      дзвінки та оздоблення.
    zh_cn: >
      想象一下，所有的电影、电视节目和音乐触手可及，可以在任何设备上播放。Jellyfin
      将您的媒体收藏转变为个性化的娱乐中心，超越传统的照片相册。您的媒体随时随地可访问，并且经过精美的组织。


      Jellyfin 是免费的开源软件，提供高质量的流媒体播放、详细的元数据和个性化推荐。多个用户可以拥有各自的媒体库。


      在像 Zima 这样的私有云设备上部署 Jellyfin，提供几乎无限的存储空间、无缝的流媒体播放和安全的多设备访问。这对于希望提升家庭媒体设置的 NAS 爱好者来说，是完美的解决方案。
  developer: Jellyfin
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/icon.png
  index: /
  is_uncontrolled: false
  main: jellyfin
  port_map: "8096"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/screenshot-3.png
  store_app_id: jellyfin-nvidia
  tagline:
    ar_sa: يضعك تحت سيطرتك على وسائطك.
    de_de: Stellt Sie in den Mittelpunkt Ihrer Medien.
    en_us: The personal Media System
    es_es: Le pone en control de sus medios.
    fr_fr: Vous met en contrôle de vos médias.
    hu_hu: Ön a média sajátos kezelésében van.
    it_it: Mette in tuo controllo i tuoi media.
    pl_pl: Umieszcza Cię w centrum swojej multimedialnej zawartości.
    pt_br: Coloca você no controle de seus meios de comunicação.
    ru_ru: Помогает вам контролировать свою медиаинформацию.
    sv_se: Lägger dig i centrum av dina medier.
    uk_ua: Помагає вам контролювати вашу медіаінформацію.
    zh_cn: 个人媒体系统
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/thumbnail.png
  tips: {}
  title:
    custom: ""
    en_us: Jellyfin(Nvidia GPU)
