- name: Install core build tools
  become: true
  package:
    name:
      - autoconf
      - automake
      - clang
      - cmake
      - gcc
      - git
      - libtool
      - make
      - meson
      - ninja-build
    state: present

- name: Install build tools (Debian)
  become: true
  package:
    name: build-essential
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install build tools (Fedora)
  become: true
  package:
    name: "@development-tools"
    state: present
  when: ansible_facts['os_family'] == "RedHat"
