- name: Install zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Set current user's shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
